version: "3.3"

services:
  app:
    image: nostalgia:latest
    volumes:
      - "config.json:/app/config.json"
      # - "folder_with_subfolders_to_sync:/data"
    command: ["/bin/sh", "-c", "npx ts-node index.ts /data | npx bunyan -o short"]
